spring:
  application:
    name: beacon-test
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.183.130:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.183.130:3306/beacon_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: dandan
  redis:
    host: 192.168.183.130
    port: 6379
server:
  port: 20000
mybatis:
  configuration:
    map-underscore-to-camel-case: true